services:

  pg_dev:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=proyecto
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3
    container_name: pg_dev
    restart: on-failure
    profiles: [ 'development' ]
    ports:
      - "5433:5432"
    volumes:
      - dev-pgdata:/var/lib/postgresql/data

  pg_prod:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=proyecto
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3
    container_name: pg_prod
    restart: on-failure
    profiles: [ 'production' ]
    ports:
      - "5434:5432"
    volumes:
      - prod-pgdata:/var/lib/postgresql/data

  pg-integration-test:
    image: postgres:16-alpine
    container_name: pg_test
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=1234
    ports:
      - "55432:5432"
    profiles: [ 'integration' ]
    tmpfs:
      - /var/lib/postgresql/data



  pgadmin:
    image: dpage/pgadmin4
    container_name: proy-pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  dev-pgdata:
  prod-pgdata:
  pgadmin-data: